#!/bin/sh
set -eux
ln -sf .config/zsh/.zshenv ~/.zshenv
exec zsh -l <<EOF
set -eux
[[ -x "$(which nvim)" ]] && exit
curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path
. ~/.cargo/env
cargo install bob-nvim ripgrep
bob use stable
EOF
