#!/bin/sh
set -eux
if [ ! -f ~/.zshenv ]; then touch ~/.zshenv; fi
grep -Fx 'ZDOTDIR="$HOME/.config/zsh"' ~/.zshenv >/dev/null ||
  echo 'ZDOTDIR="$HOME/.config/zsh"' >> ~/.zshenv
grep -Fx '[[ ! -o interactive ]] && TRAPUSR1(){}' ~/.zshenv >/dev/null ||
  echo '[[ ! -o interactive ]] && TRAPUSR1(){}' >> ~/.zshenv
exec zsh -l <<EOF
set -eux
[[ -x "$(which nvim)" ]] && exit
curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path
. ~/.cargo/env
cargo install bob-nvim ripgrep
bob use stable
EOF
