set -sg escape-time 0

unbind C-b
set -g prefix C-z
bind C-z send-prefix

set -g mouse on

set-window-option -g mode-keys vi

bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

set-hook -g client-attached 'run-shell -b "~/.config/tmux/repoint-agent.sh #{q:session_id}"'
